controllers:
    resource:
        path: ../src/Api/
        namespace: App\Api
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }


